"""
Generates rpp (rules++) source: https://github.com/Aerll/rpp

Unlike DDNet's `.rules`, rpp can express an ANY neighbor by simply not mentioning that position,
so this reads the tiles as the user configured them instead of the expanded 256-slot table.
"""
from collections import defaultdict
from typing import Dict, List, Optional, Sequence

from src.backend.neighbor import Neighbor
from src.backend.tile_connection import TileConnection
from src.backend.tile_data import TileData
from src.backend.tile_group import GroupMode, TileGroup
from src.backend.tile_status import TileStatus


def dumps(tiles: Dict[int, TileData], rule_name: str, image_stem: str,
          groups: Optional[Sequence[TileGroup]] = None) -> str:
    groups = list(groups or [])
    rules = sorted(_collectRules(tiles), key=lambda rule: rule.sortKey())

    header = ("// generated by SimpleDDNetAutomapper, edits will be lost\n"
              "// compile with rpp (https://github.com/Aerll/rpp), base.r has to sit next to this file\n"
              '#include "base.r"\n'
              f'#output "{image_stem}.rules"\n'
              "\n")
    if groups:
        header += "".join(f"object {group.name} = Rect({group.top_left}, {group.bottom_right});\n"
                          for group in groups) + "\n"

    body = f'AutoMapper("{rule_name}");\nNewRun();\n\n'
    body += "".join(f"{line}\n" for line in _insertLines(rules))
    return header + body + _groupRuns(groups)


class _Rule:
    def __init__(self, tile_id: int, variant: int, con: TileConnection, status: TileStatus, chance: float):
        neighbors = con.getNeighbors()
        self.tile_id = tile_id
        self.variant = variant
        self.chance = chance
        self.index = f"{tile_id}{_rotationSuffix(status)}"
        # 2 is ANY, and an ANY position is simply left out
        self.full = tuple(n.rppName for n, state in zip(Neighbor, neighbors) if state == 1)
        self.empty = tuple(n.rppName for n, state in zip(Neighbor, neighbors) if state == 0)

    def testKey(self):
        return self.full, self.empty

    def sortKey(self):
        # ANY makes rules overlap: "top empty" also matches "top empty, left full". DDNet keeps the
        # last rule that matched, so the more specific one has to be written after the general one.
        return len(self.full) + len(self.empty), self.tile_id, self.variant


def _collectRules(tiles: Dict[int, TileData]) -> List[_Rule]:
    rules = []
    for tile_id, tile in sorted(tiles.items()):
        # flips and rotations have to be expanded, each one tests a different neighborhood. ANY does
        # not: rpp expresses it by leaving the position out, which is what `.rules` cannot do.
        for variant, (con, status) in enumerate(tile.getAllPossibleModifications()):
            rules.append(_Rule(tile_id, variant, con, status, tile.chance))
    return rules


def _insertLines(rules: List[_Rule]) -> List[str]:
    # tiles asking the very same question are the ones competing for a spot, so they go into one
    # Insert and let rpp randomize between them
    pools = defaultdict(list)
    for rule in rules:
        pools[rule.testKey()].append(rule)
    return [_insertLine(pool) for pool in pools.values()]


def _insertLine(pool: List[_Rule]) -> str:
    chances = [rule.chance for rule in pool]
    line = f"Insert({', '.join(rule.index for rule in pool)})"
    if len(set(chances)) > 1:
        # rpp takes the shares as given, util:Unbias scales them down if they add up to more than 100
        line += f".Chance({', '.join(f'{chance:g}' for chance in chances)})"
    elif len(chances) > 1:
        line += ".Roll()"  # equal shares, which is what Roll means
    elif chances[0] < 100:
        line += f".Chance({chances[0]:g})"

    first = pool[0]
    tests = ""
    if first.full:
        tests += f".IsFullAt({', '.join(first.full)})"
    if first.empty:
        tests += f".IsEmptyAt({', '.join(first.empty)})"
    if not tests:
        return f"{line};"  # every neighbor is ANY, so only the implied Pos 0 0 FULL is left
    return f"{line}.If(IndexAt([0, 0]){tests});"


def _groupRuns(groups: List[TileGroup]) -> str:
    if not groups:
        return ""

    # OverrideLayer makes an anchor visible to the tiles scanned after it, which is what lets
    # IsNotOverlapping see the claims that earlier placements already made
    lines = ["\nNewRun();\nOverrideLayer();\n"]
    lines += [_insertObject(group, groups) for group in groups]
    # the anchor is the only tile InsertObject writes, FillObjects paints the rest of the footprint
    lines.append("\nNewRun();\nOverrideLayer();\nRun().FillObjects();\n")
    return "".join(lines)


def _insertObject(group: TileGroup, everyone: List[TileGroup]) -> str:
    # checked against every group, itself included: two anchors of the same group collide just as
    # easily as two different ones
    chance = f".Chance({group.chance:g})" if group.chance < 100 else ""
    tests = ["Object().HasSpace()",
             f"Object().IsNotOverlapping({', '.join(other.name for other in everyone)})"]
    if group.mode is GroupMode.DECORATE:
        ring = ", ".join(f"[{x}, {y}]" for x, y in group.ringOffsets())
        tests.append(f"IndexAt({ring}).IsFull()")

    body = ",\n".join(f"    {test}" for test in tests)
    return f"InsertObject({group.name}){chance}.If(\n{body}\n);\n"


def _rotationSuffix(status: TileStatus) -> str:
    # rpp spells it V/H/R: V is our x_flip (XFLIP), H is y_flip (YFLIP), R is rot (ROTATE)
    suffix = ("V" if status.x_flip else "") + ("H" if status.y_flip else "") + ("R" if status.rot else "")
    return f".{suffix}" if suffix else ""
