import math

# Tileset
TILESET_ROW = 16
TILESET_COL = 16
NUM_TILES = TILESET_ROW * TILESET_COL

# Neighbor relation
EIGHT_NEIGHBORS = 8
NUM_NEIGHBOR_STATES=3
NUM_NEIGHBOR_BITS=int(math.ceil(NUM_NEIGHBOR_STATES/2))
NEIGHBOR_BIT_COMPERATOR=0
for i in range(NUM_NEIGHBOR_BITS):
    NEIGHBOR_BIT_COMPERATOR+= (1 << i)
assert NEIGHBOR_BIT_COMPERATOR == 3
