name: Build SimpleDDNetAutomapper

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11']
        architecture: ['x64']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install PyQt5
        run: pip install -r requirements.txt

      - name: Build Executable for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller -F src/viewer.py
          mv dist/viewer dist/viewer_linux_python_${{ matrix.python-version }}

      - name: Build Executable for Windows
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller -F src/viewer.py
          mv dist/viewer.exe dist/viewer_win64_python${{ matrix.python-version }}.exe

      - name: Upload Artifacts
        if: matrix.python-version == '3.11'
        uses: actions/upload-artifact@v4
        with:
          name: simple_ddnet_automapper_${{ matrix.os }}${{ matrix.architecture }}
          path: dist/
