name: Test Code with Pytest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ '3.10', '3.11' ]
        architecture: [ 'x64' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install LibEGL
        if: matrix.os == 'ubuntu-latest'
        run: |
          : # https://askubuntu.com/questions/1485442/issue-with-installing-pyqt6-on-ubuntu-22-04
          sudo apt update && sudo apt install libegl1 -y
          sudo apt-get install -qq libglu1-mesa-dev libx11-xcb-dev '^libxcb*'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest
