name: Test Code with Pytest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ '3.10', '3.11' ]
        architecture: [ 'x64' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install Missing libs
        if: matrix.os == 'ubuntu-latest'
        run: |
          : # https://askubuntu.com/questions/1485442/issue-with-installing-pyqt6-on-ubuntu-22-04
          sudo apt update
          sudo apt-get install -y libegl1
          sudo apt-get install -y libxcb-xinerama0
          sudo apt-get install -y -qq libglu1-mesa-dev libx11-xcb-dev '^libxcb*'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests (without QApplication)
        if: matrix.os == 'ubuntu-latest'
        run: |
          : # as long as this bug is present I can't test this in the pipeline, PyQt6 doesn't install well on ubuntu
          pytest -m "not requires_q_app"

      - name: Run Tests (with QApplication)
        if: matrix.os != 'ubuntu-latest'
        run: pytest
